---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: nt-gaming-os
# description will be included in the image's metadata
description: An OS with pre-installed gaming software just for me.

# the base image to build on top of (FROM) and the version tag to use
base-image:  ghcr.io/ublue-os/bazzite-gnome-nvidia-open
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/scottames/zen-browser/
    install:
      - zen-browser
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - dev.zed.Zed
        - dev.vencord.Vesktop

  # Install 1Password.
  - type: bling
    install:
      - 1password

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

